version: '2.0'
services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

    command: mongod --logpath=/dev/null
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: express
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    restart: unless-stopped


