# local MongoDB replica set (single node) with MongoExpress
# Modified base on Anthony Simmon
# https://medium.com/workleap/the-only-local-mongodb-replica-set-with-docker-compose-guide-youll-ever-need-2f0b74dd8384
#
# for linux, add DNS record '127.17.0.1 host.docker.internal' to /etc/hosts
# add '?replicaSet=rs0' to connection URL
# Example :
#     mongodb://host.docker.internal:27017/?replicaSet=rs0&ssl=false

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

  mongo-express:
    image: mongo-express
    container_name: express
    links:
      - mongo
    ports:
      - 8081:8081

    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    restart: unless-stopped

volumes:
  mongo_data:
  mongo_config:

